; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc1-n16r8]
platform=https://github.com/pioarduino/platform-espressif32.git#51.03.07
board = esp32-s3-devkitc-1
lib_deps =
  https://github.dev/fabian222005/FabGL.git#esp32s3
framework = espidf, arduino
monitor_speed = 115200
lib_ldf_mode = deep+
board_build.arduino.memory_type = qio_opi
debug_build_flags= -O0 -g -ggdb
monitor_filters= esp32_exception_decoder
build_type= debug
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_build.f_flash = 80000000L
board_build.boot_freq =120000000L
board_build.embed_txtfiles=
  managed_components/espressif__esp_insights/server_certs/https_server.crt
  managed_components/espressif__esp_rainmaker/server_certs/rmaker_mqtt_server.crt
  managed_components/espressif__esp_rainmaker/server_certs/rmaker_claim_service_server.crt
  managed_components/espressif__esp_rainmaker/server_certs/rmaker_ota_server.crt
build_flags =
    -DARDUINO_ESP32S3_DEVKITC1_N16R8
    -DARDUINO_ARCH_ESP32S3
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCONFIG_IDF_TARGET_ESP32S3
    -DHSPI_HOST=1
    -DCORE_DEBUG_LEVEL=5
    -DLOG_LOCAL_LEVEL=ESP_LOG_VERBOSE